---

- name: configure hostname
  hostname:
    name: "{{ inventory_hostname }}.{{ domain }}"

- name: update all packages
  package:
    name: "*"
    state: latest
  when: ansible_os_family != "Alpine"

- name: upgrade all packages
  apk:
    upgrade: yes
  when: ansible_os_family == "Alpine"

  # If multiple distros are used put this into variable
- name: install auditd
  package:
    name: audit

- name: enable and start auditd
  service:
    name: auditd
    enabled: yes
    state: started

- name: Install tzdata
  package:
    name: tzdata

- name: configure timezone
  timezone:
    name: '{{ timezone }}'

- name: generate ssh key for root user
  openssh_keypair:
    path: "/root/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no
  when: packer is undefined

- name: configure journald
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - journald.conf
  notify:
    - restart journald
  when: ansible_facts.service_mgr == "systemd"

- name: install logrotate
  package:
    name: logrotate
    state: present

- name: configure logrotate
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0644

# Outdate: due to daily cron job

# - name: enable and start logrotate
#   service:
#     name: logrotate.timer
#     enabled: yes
#     state: started
