---

- name: postgres deployment
  hosts: postgres
  remote_user: root
  roles:
    - { role: docker }
    - { role: certbot, cert_domain: 'pg.{{ domain }}' }
    - { role: postgres, db_domain: 'pg.{{ domain}}' }
