---

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
  listen: Restart firewalld

- name: Start firewalld
  service:
    name: firewalld
    state: started
  listen: Restart firewalld
