---

- name: Debug
  debug:
    msg: "{{ ansible_all_ipv4_addresses | ipaddr('10.0.0.0/8') | first }}"

- name: generate postgres filestructure
  file:
    path: '/containers/postgres/{{ item.path }}'
    state: directory
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  with_items:
    - { path: '/var/lib/postgresql/data', owner: 'root', group: '999' }

- name: deploy postgres container
  docker_container:
    name: postgres
    image: docker.io/library/postgres:13
    restart_policy: always
    ports:
      - "{{ ansible_all_ipv4_addresses | ipaddr('10.0.0.0/8') | first }}:5432:5432"
    env:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_USER: '{{ pg_user }}'
      POSTGRES_PASSWORD: '{{ pg_default_password }}'
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

- name: create postgres configuration files
  template:
    src: '{{ item }}.j2'
    dest: /containers/postgres/var/lib/postgresql/data/{{ item }}
    owner: '999'
    group: '999'
    mode: 0600
  with_items:
    - postgresql.conf
    - pg_hba.conf

- name: install postgres certificates
  copy:
    src: /containers/certbot_{{db_domain}}/etc/letsencrypt/live/{{ db_domain }}/{{ item.cert }}
    dest: '/containers/postgres/{{ item.dest }}'
    remote_src: true
    owner: '999'
    group: '999'
    mode: 0400
  with_items:
    - { cert: 'cert.pem', dest: '{{ pg_ssl_cert_file }}' }
    - { cert: 'chain.pem', dest: '{{ pg_ssl_ca_file }}' }
    - { cert: 'privkey.pem', dest: '{{ pg_ssl_key_file }}' }
  when: pg_ssl == 'on'

- name: restart postgres container
  docker_container:
    name: postgres
    state: started
    restart: yes

- name: configure firewalld
  firewalld:
    zone: public
    service: postgresql
    permanent: yes
    state: enabled

- name: install psycopg2
  pip:
    name: psycopg2-binary
    state: present

- name: Update postgres password
  postgresql_user:
    login_host: 127.0.0.1
    login_user: '{{ pg_user }}'
    login_password: '{{ pg_default_password }}'
    name: '{{ pg_user }}'
    password: '{{ pg_password }}'
    ssl_mode: require
