---
- name: Creation of base image
  hosts: all
  remote_user: root
  vars_files:
    - ../../group_vars/all/common.yml
    - ../../group_vars/all/root_access.yml
    - ../../group_vars/all/users.yml
    - ../../group_vars/all/firewall.yml

  vars:
    - packer: yes

  roles:
    - { role: python }
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root }
    - { role: tiny-cloud }
    - { role: firewall }
