---

- name: make sure .ssh directory exists.
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: add authorized keys for root
  template:
    src: authorized_keys.j2
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600
