---

- name: install firewalld
  apt:
    name: firewalld
    state: present

- name: configure firewalld
  template:
    src: firewalld.conf.j2
    dest: /etc/firewalld/firewalld.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart firewalld

- name: start & enable firewalld
  service:
    name: firewalld
    enabled: yes
    state: started
