---
- name: install sys, devops & utils tools
  dnf:
    name:
      - nmap
      - net-tools
      - rsync
      - mtr
      - tree
      - sysstat
      - tcpdump
      - traceroute
      - vnstat
      - ncdu
      - zsh
      - ipcalc
      - neovim
      - the_silver_searcher
      - wget
      - curl

- name: start & enable vnstatd
  service:
    name: vnstat
    enabled: yes
    state: started
