---

# - name: remove all users from sudo group
#   command: groupmems -g sudo --purge
#   register: groupmemes
#   changed_when: "groupmems.rc == 0"

# - name: create sudo users
#   user:
#     name: {{ item.key }}
#     group: sudo
#     groups: "{{ item.value.groups + [ 'sudo' ] | join(',') }}"
#     comment: "{{ item.value.name }}"
#     password: ""
#     update_password: on_create
#     state: present

- name: allow sudo users to use sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo ALL=\(ALL:ALL\) ALL'
    insertafter: '^# %sudo ALL=\(ALL:ALL\) ALL'
    line: '%sudo ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'
    mode: 0440
    owner: root
    group: root
