---

- name: install sudo
  dnf:
    name: sudo
    state: present

- name: remove all users from wheel group
  command: groupmems -g wheel --purge
  register: groupmems
  changed_when: "groupmems.rc == 0"

- name: add sudo users to wheel group
  user:
    name: '{{ item }}'
    append: yes
    groups: 
      - wheel
  with_items: '{{ sudo_users }}'

- name: allow sudo users to use sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel ALL=\(ALL:ALL\) ALL'
    insertafter: '^# %sudo ALL=\(ALL:ALL\) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'
    mode: 0440
    owner: root
    group: root
