---

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Download migrate2rocky
  get_url:
    url: https://cdn.githubraw.com/rocky-linux/rocky-tools/main/migrate2rocky/migrate2rocky.sh
    dest: /tmp/migrate2rocky.sh
    mode: 0110
  when: ansible_distribution != "Rocky"

- name: Add exit to migrate2rocky.sh
  lineinfile:
    path: /tmp/migrate2rocky.sh
    insertafter: 'EOF'
    line: 'exit 0'
  when: ansible_distribution != "Rocky"

- name: Run migrate2rocky.sh
  shell:
    cmd: /tmp/migrate2rocky.sh -r
  when: ansible_distribution != "Rocky"

- name: Reboot server
  reboot:
    reboot_timeout: 300

- name: Remove migrate2rocky.sh
  file:
    path: /tmp/migrate2rocky.sh
    state: absent
