---

- name: Install awall
  package:
    name: awall
    state: present

- name: Load iptables module
  modprobe:
    name: ip_tables
    state: present

- name: Enable ip(6)tables service
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - iptables
    - ip6tables

- name: Deploy standard awall rules
  template: 
    src: awall-template.j2
    dest: /etc/awall/optional/{{ item.key }}.json
    owner: root
    group: root
    mode: 0644
  with_dict: '{{ awall_default_rules }}'

- name: Debug
  debug:
    var: awall_service_rules

- name: Deploy specific service awall rules.
  template:
    src: awall-template.j2
    dest: /etc/awall/optional/{{ item.key }}.json
    owner: root
    group: root
    mode: 0644
  with_dict: '{{ awall_service_rules }}'
  when: awall_service_rules is defined

- name: find all files in /etc/awall/optional/
  find:
    paths: /etc/awall/optional
    recurse: no
    file_type: file
  register: found_policies

- name: Enable awall policies
  awall:
    name: '{{ item.path.split(".") | first | basename }}'
    state: enabled
  with_items: '{{ found_policies.files }}'

- name: Activate firewall rules
  awall:
    activate: true
  
- name: Configure sysctl
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
  with_items:
    # DROP ICMP echo-requests sent to broadcast or multicast
    - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 } 
    # Drop source routed packets
    - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
    # Enable TCP SYN cookie protection from SYN floods
    - { name: net.ipv4.tcp_syncookies, value: 1 }
    # Don't accept ICMP redirect messages
    - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
    # Don't send ICMP redirect messages
    - { name: net.ipv4.conf.all.send_redirects, value: 0 }
    # Enable source address spoofing protection
    - { name: net.ipv4.conf.all.rp_filter, value: 1 }
    # Log packets with impossible source addresses
    - { name: net.ipv4.conf.all.log_martians, value: 1 }
