---


- name: copy postgres.conf template to host
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/postgresql.conf
    owner: '999'
    group: '999'

- name: change permissions on certs
  file:
    path: '/etc/letsencrypt/live/{{ db_domain }}'
    state: directory
    owner: 'root'
    group: '999'
    mode: 0640
    recurse: yes

- name: deploy postgres container
  containers.podman.podman_container:
    name: postgres
    image: docker.io/library/postgres:13
    restart_policy: always
    ports:
      - 5432:5432
    env:
      POSTGRES_USER: '{{ pg_user }}'
      POSTGRES_PASSWORD: '{{ pg_password }}'
    volumes:
      - /etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - /etc/letsencrypt/live/{{ db_domain }}/privkey.pem:/etc/postgresql/certs/privkey.pem
      - /etc/letsencrypt/live/{{ db_domain }}/fullchain.pem:/etc/postgresql/certs/fullchain.pem
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    command: |
      -c config_file=/etc/postgresql/postgresql.conf
      

- name: configure firewalld
  firewalld:
    zone: public
    service: postgresql
    permanent: yes
    state: enabled

- name: install psycopg2
  pip:
    name: psycopg2-binary
    state: present

- name: create test database
  postgresql_db:
    login_host: 135.181.42.75
    login_user: '{{ pg_user }}'
    login_password: '{{ pg_password }}'
    maintenance_db: '{{ pg_user }}'
    name: postgres
    owner: '{{ pg_user }}'
