---

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: true

- name: restart syslog-ng
  systemd:
    name: syslog-ng
    state: restarted

- name: restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted

